AppName: Test
Account: "123456789012"
Region: ap-southeast-2
Kms:
  key-admin-arns:
    - arn:aws:iam::123456789012:role/key-admin
    - arn:aws:iam::123456789012:role/deploy-role
Secrets:
  is-single-object-secret: false
  env:
    SECRET_1:
      description: Test secret 1
    SECRET_2:
      description: Test secret 2
Tags:
  CostCentre: TODO
  Project: TODO
