AWSTemplateFormatVersion: '2010-09-09'
Description: Create an AWS CloudTrail trail capturing AWS API calls made by your AWS
  account and publishing the logs to an Amazon S3 bucket and SNS Topic.
Parameters:
  BucketName:
    Description: Name of the S3 bucket.
    Type: String
    Default: name-cloudtrail
  TopicName:
    Description: Name of the SNS topic.
    Type: String
    Default: CloudTrail-SNS
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'BucketName'
      AccessControl: AuthenticatedRead
      VersioningConfiguration:
        Status: Suspended
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'S3Bucket'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}'
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/main/AWSLogs/${AWS::AccountId}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref 'TopicName'
      DisplayName: !Ref 'TopicName'
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref 'SNSTopic'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailSNSPolicy
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action:
              - SNS:Publish
            Resource: !Ref 'SNSTopic'
  Trail:
    Type: AWS::CloudTrail::Trail
    DependsOn:
      - S3BucketPolicy
      - SNSTopicPolicy
    Properties:
      IncludeGlobalServiceEvents: true
      IsLogging: true
      S3KeyPrefix: main
      S3BucketName: !Ref 'S3Bucket'
      SnsTopicName: !Ref 'SNSTopic'
