version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    groups:
      all-dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      time: "08:00"
      timezone: Australia/Melbourne

  - package-ecosystem: pip
    directory: "/"
    groups:
      all-dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Australia/Melbourne
    open-pull-requests-limit: 1

  - package-ecosystem: pip
    directory: "/_common"
    groups:
      all-dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Australia/Melbourne
    open-pull-requests-limit: 1
