AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create S3 bucket with encryption, logging and versioning enabled for storing configs (e.g. Docker).
Parameters:
  BucketName:
    Description: The name of the S3 bucket to be created.
    Default: sample-service-configs
    Type: String
  BucketRootLogName:
    Description: >-
      The name of the existing S3 bucket for logging (see S3-RootLogs.template).
    Type: String
  BillingTag:
    Description: The value of the Billing tag to be added to the S3 bucket.
    Type: String
  ReplicationDestinationBucket:
    Description: The destination bucket ARN for cross-region replication.
    Type: String
  ReplicationRoleArn:
    Description: The IAM role ARN for S3 replication.
    Type: String
  ReplicationDestinationBucket:
    Description: The destination bucket ARN for cross-region replication.
    Type: String
  ReplicationRoleArn:
    Description: The IAM role ARN for S3 replication.
    Type: String
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: BucketOwnerFullControl
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref BucketRootLogName
        LogFilePrefix: !Join
          - ''
          - - !Ref BucketName
            - /
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !Ref ReplicationRoleArn
        Rules:
          - Id: ReplicateEverything
            Status: Enabled
            Prefix: ''
            Destination:
              Bucket: !Ref ReplicationDestinationBucket
              StorageClass: STANDARD_IA
      ReplicationConfiguration:
        Role: !Ref ReplicationRoleArn
        Rules:
          - Id: ReplicateEverything
            Status: Enabled
            Prefix: ''
            Destination:
              Bucket: !Ref ReplicationDestinationBucket
              StorageClass: STANDARD_IA
      Tags:
        - Key: Billing
          Value: !Ref 'BillingTag'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
