---
swagger: "2.0"
info:
  description: "K-SFN-API"
  title: "K-SFN-API"
host: "todo_api_id.execute-api.todo_region.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /execution:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:todo_region:lambda:path/2015-03-31/functions/arn:aws:lambda:todo_region:1231456789012:function:K-SFN-Function-B:${stageVariables.lambdaAlias}/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        credentials: "arn:aws:iam::1231456789012:role/K-SFN-API-ExecutionRole"
        uri: "arn:aws:apigateway:todo_region:states:action/StartExecution"
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/json: "{\n  \"token\": \"$input.json('$.executionArn').split(':')[7].replace('\"\
                ', \"\")\"\n}"
        requestTemplates:
          application/json: "{\n    \"input\": \"$util.escapeJavaScript($input.json('$'))\"\
            ,\n    \"stateMachineArn\": \"${stageVariables.sfnArn}\"\n}"
        passthroughBehavior: "when_no_templates"
        httpMethod: "POST"
        type: "aws"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
x-amazon-apigateway-gateway-responses:
  WAF_FILTERED:
    statusCode: 403
    responseParameters:
      gatewayresponse.header.Reason: "'WAF FIltered'"
    responseTemplates:
      application/json: "{\"message\":$context.error.messageString}"
  MISSING_AUTHENTICATION_TOKEN:
    statusCode: 403
    responseParameters:
      gatewayresponse.header.reason: "'missing authentication token'"
    responseTemplates:
      application/json: "{\"message\":$context.error.messageString}"
  INVALID_SIGNATURE:
    statusCode: 403
    responseParameters:
      gatewayresponse.header.Reason: "'Invalid API signature'"
    responseTemplates:
      application/json: "{\"message\":$context.error.messageString}"
  ACCESS_DENIED:
    statusCode: 403
    responseParameters:
      gatewayresponse.header.Reason: "'AccessDenied'"
    responseTemplates:
      application/json: "{\"message\":$context.error.messageString}"
  INVALID_API_KEY:
    statusCode: 403
    responseParameters:
      gatewayresponse.header.Reason: "'Invalid API key'"
    responseTemplates:
      application/json: "{\"message\":$context.error.messageString}"
