AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 bucket for logging.

Parameters:
  BucketExportName:
    Description: The name of exported bucket name.
    Type: String
    Default: MyAppLogsBucket
  BucketName:
    Description: The name of the logs bucket to be created for logging.
    Type: String
    Default: my-app-logs
  TagBillingValue:
    Description: The value of the Billing tag to be added to the S3 bucket.
    Type: String

Resources:
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
          - Id: DeleteContentAfter1Day
            Status: Enabled
            ExpirationInDays: 1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Billing
          Value: !Ref TagBillingValue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

Outputs:
  BucketName:
    Description: Name of the logs bucket.
    Value: !Ref LogsBucket
    Export:
      Name: !Ref BucketExportName
