AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template deploys additional CloudWatch Alarms and SNS email notifications
  (not Auto Scaling).

Parameters:
  ApiGatewayAlarmEmail:
    Description: Email address to notify if there are any API Gateway operational issues
    Type: String
  ApiName:
    Description: Name of the API Gateway
    Type: String

Resources:
  ApiGatewayAlarmSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref ApiGatewayAlarmEmail
          Protocol: email

  ApiGateway4XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref ApiGatewayAlarmSnsTopic
      AlarmDescription: When API Gateway 4XX error occurs it will be notified through SNS
      AlarmName: !Join ['/', ['apigateway', !Ref ApiName, 'v1', '4XXError']]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref ApiName
        - Name: Stage
          Value: v1
      EvaluationPeriods: 1
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Period: 300
      Statistic: Sum
      Threshold: 0
      TreatMissingData: notBreaching

  ApiGateway5XXErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref ApiGatewayAlarmSnsTopic
      AlarmDescription: When API Gateway 5XX error occurs it will be notified through SNS
      AlarmName: !Join ['/', ['apigateway', !Ref ApiName, 'v1', '5XXError']]
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref ApiName
        - Name: Stage
          Value: v1
      EvaluationPeriods: 1
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Period: 300
      Statistic: Sum
      Threshold: 0
      TreatMissingData: notBreaching

Outputs:
  ApiGatewayAlarmSnsTopicArn:
    Description: A reference to SNS Notification ARN of API Gateway error activities
    Value: !Ref ApiGatewayAlarmSnsTopic
