AWSTemplateFormatVersion: "2010-09-09"

Description: Create a ECR repository

Parameters:
  RepoName:
    Description: Repository name
    Type: String

Resources:
  EcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepoName
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
            {
              "rulePriority": 1,
              "description": "Only keep 5000 images",
              "selection": {
                "tagStatus": "any",
                "countType": "imageCountMoreThan",
                "countNumber": 5000
              },
              "action": { "type": "expire" }
            }]
          }
