AWSTemplateFormatVersion: '2010-09-09'

Description: Create IAM Group for pull images from ECR

Parameters:
  IamGroupNameECRPullOnly:
    Description: Name of the IAM Group to be created
    Type: String

Resources:
  IamGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref 'IamGroupNameECRPullOnly'

  IamPolicyPullOrcaECR:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Groups:
        - !Ref 'IamGroup'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ecr:DescribeRepositories
              - ecr:ListImages
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:GetAuthorizationToken
              - ecr:GetRepositoryPolicy
            Resource: '*'
