# Stack name: ApiGateway-CloudWatchLogs
AWSTemplateFormatVersion: '2010-09-09'

Description: Grant the entire API Gateway service proper permissions to read and write
  logs to CloudWatch for your account. You need to do this once.
  See https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-cloudwatch-logs/.

Resources:
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchLogRole.Arn

  ApiGatewayCloudWatchLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      RoleName: APIGatewayPushToCloudWatchLogRole

Outputs:
  ApigCloudWatchLogRoleName:
    Description: The name of the API Gateway CloudWatch Log Role
    Value: !Ref ApiGatewayCloudWatchLogRole
  ApigCloudWatchLogRoleArn:
    Description: The ARN of the API Gateway CloudWatch Log Role
    Value: !GetAtt ApiGatewayCloudWatchLogRole.Arn
