AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Create KMS Key and Key policies which are resource policies that control access to the Customer Master Keys (CMKs).

Parameters:
  KeyAdminRoleArn:
    Description: The ARN of the key admin role
    Type: String
  KmsAliasName:
    Description: Key alias
    Type: String

Resources:
  KmsKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      EnableKeyRotation: True
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: EnableRootAccessAndPreventPermissionDelegation
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: "*"
            Condition:
              StringEquals:
                "aws:PrincipalType": Account

          # Key administrators can admin keys, not use them.
          # Permissions granted via IAM policy, or key policy, or both.
          - Sid: Allow access for Key Administrators
            Effect: Allow
            Principal:
              AWS: !Ref KeyAdminRoleArn
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:TagResource
              - kms:UntagResource
              - kms:ScheduleKeyDeletion  # allow for key deletion
              - kms:CancelKeyDeletion    # allow for key deletion
            Resource: "*"

          - Sid: Allow access through EBS for all principals in the account that are authorized to use EBS
            Effect: Allow
            Principal:
              AWS: "*"
            Condition:
              StringEquals:
                kms:CallerAccount: !Ref AWS::AccountId
                kms:ViaService: !Sub ec2.${AWS::Region}.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Resource: "*"

  KmsAlias:
    Type: AWS::KMS::Alias
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AliasName: !Sub alias/${KmsAliasName}
      TargetKeyId: !Ref KmsKey

Outputs:
  KmsKeyArn:
    Description: KmsKeyArn
    Value: !GetAtt KmsKey.Arn
