AWSTemplateFormatVersion: '2010-09-09'
Description: Create a CodeArtifact Domain with KMS encryption key and Domain policy

Parameters:
  DomainName:
    Description: A string that specifies the name of the requested domain.
    Type: String
  OrgId:
    Description: Organization ID
    Type: String

Resources:
  CodeArtifactDomain:
    Type: AWS::CodeArtifact::Domain
    Properties:
      DomainName: !Ref DomainName
      # TODO EncryptionKey: arn:aws:kms:us-west-2:123456789012:key/12345678-9abc-def1-2345-6789abcdef12

      # Domain Policy gives you the ability to specify which actions other AWS accounts and organizations can perform on your domain.
      PermissionsPolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - codeartifact:CreateRepository
              - codeartifact:DescribeDomain
              - codeartifact:GetAuthorizationToken
              - codeartifact:GetDomainPermissionsPolicy
              - codeartifact:ListRepositoriesInDomain
            Principal: "*"
            Resource: "*"
            Condition:
              StringEquals:
                aws:PrincipalOrgId:
                  - !Ref OrgId

Outputs:
  CodeArtifactDomain:
    Value: !Ref CodeArtifactDomain
  CodeArtifactDomainArn:
    Value: !GetAtt CodeArtifactDomain.Arn
  CodeArtifactDomainEncryptionKey:
    Value: !GetAtt CodeArtifactDomain.EncryptionKey
  CodeArtifactDomainName:
    Value: !GetAtt CodeArtifactDomain.Name
    Export:
      Name: main:codeartifact:domain:name
  CodeArtifactDomainOwner:
    Value: !GetAtt CodeArtifactDomain.Owner
