name: Lint

on:
  push:
    paths:
      - .github/**
      - '**/cfn/*.yaml'

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run yamllint and cfn-lint with common config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Run lint
        run: make lint
