name: Lint

on:
  push:
    paths:
      - .github/**
      - '**/cfn/*.yaml'

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run yamllint and cfn-lint with common config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@master

      - name: Run yamllint
        run: yamllint -c ./.github/linters/.yaml-lint.yaml -f parsable --format standard .github/

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Run cfn-lint
        run: cfn-lint --config-file .github/linters/.cfnlintrc
